export default [
  {
    id: 1,
    name: "Alounyadeth",
    lastName: "Sihamaya",
    photo: "https://i.postimg.cc/Y24fpT41/andrew.jpg",
    generalComputing: "A",
    mathematics: "A",
    computerRepair: "A",
    laws: "B",
    english: "A",
    informationTech: "A",
    link: "/andrew",
  },
  {
    id: 2,
    name: "Phutthasin",
    lastName: "Matthouchan",
    photo: "https://i.postimg.cc/rmpLBwVc/kong.jpg",
    generalComputing: "A",
    mathematics: "B",
    computerRepair: "B",
    laws: "B+",
    english: "A",
    informationTech: "C+",
    link: "/kong",
  },
  {
    id: 3,
    name: "Phutthason",
    lastName: "Matthouchan",
    photo: "https://i.postimg.cc/0NnsXwqc/kob.jpg",
    generalComputing: "A",
    mathematics: "B",
    computerRepair: "B",
    english: "B",
    laws: "A",
    informationTech: "C+",
    link: "/kob",
  },
  {
    id: 4,
    name: "Hongvilay",
    lastName: "Phathammavong",
    photo: "https://i.postimg.cc/x8JVdpN4/bm.jpg",
    generalComputing: "A",
    mathematics: "B",
    computerRepair: "C+",
    laws: "A",
    english: "B+",
    informationTech: "C+",
    link: "/bm",
  },
  {
    id: 5,
    name: "Thanabat",
    lastName: "Phommexay",
    photo: "https://i.postimg.cc/yNy1qG0h/boss.jpg",
    generalComputing: "A",
    mathematics: "C+",
    computerRepair: "C+",
    laws: "B+",
    english: "C+",
    informationTech: "C+",
    link: "/boss",
  },
  {
    id: 6,
    name: "Thunwa",
    lastName: "Phongsa",
    photo: "https://i.postimg.cc/SsZmRzTJ/tick.jpg",
    generalComputing: "A",
    mathematics: "C+",
    computerRepair: "C+",
    laws: "C+",
    english: "C+",
    informationTech: "C+",
    link: "/tick",
  },
  {
    id: 7,
    name: "Vouthisack",
    lastName: "Sirisouk",
    photo: "https://i.postimg.cc/zBDJqkks/sack.jpg",
    generalComputing: "A",
    mathematics: "C+",
    computerRepair: "C",
    laws: "C+",
    english: "B",
    informationTech: "C+",
    link: "/sack",
  },
  {
    id: 8,
    name: "Phoutavan",
    lastName: "Phunthavong",
    photo: 'https://i.postimg.cc/tTmHpGJ6/alex.jpg',
    generalComputing: "A",
    mathematics: "C+",
    computerRepair: "C",
    laws: "C+",
    english: "B",
    informationTech: "C+",
    link: "/alex",
  },
  {
    id: 9,
    name: "Phoutthavong",
    lastName: "Thepvongsa",
    photo: "https://i.postimg.cc/CxjYD2ry/ter.jpg",
    generalComputing: "A",
    mathematics: "B+",
    computerRepair: "A",
    laws: "B",
    english: "B+",
    informationTech: "A",
    link: "/peter",
  },
  {
    id: 10,
    name: "Kamonlat",
    lastName: "Sasawat",
    photo: "https://i.postimg.cc/gjQdqbPp/ning.jpg",
    generalComputing: "A",
    mathematics: "A",
    computerRepair: "A",
    laws: "A",
    english: "B+",
    informationTech: "B+",
    link: "/ning",
  },
  {
    id: 11,
    name: "Inpaeng",
    lastName: "Panyakhoun",
    photo: "https://i.postimg.cc/9Q3CD2pt/paeng.jpg",
    generalComputing: "B+",
    mathematics: "B",
    computerRepair: "A",
    laws: "B",
    english: "B",
    informationTech: "B",
    link: "/paeng",
  },
  {
    id: 12,
    name: "Jedsada",
    lastName: "Siviengxay",
    photo: "https://i.postimg.cc/vmbyvvC4/jed.jpg",
    generalComputing: "A",
    mathematics: "C",
    computerRepair: "B",
    laws: "F",
    english: "C+",
    informationTech: "B",
    link: "/jed",
  },
  {
    id: 13,
    name: "Chanthala",
    lastName: "Khamone",
    photo: "https://i.postimg.cc/WpH2Pgqy/bank.jpg",
    generalComputing: "A",
    mathematics: "C+",
    computerRepair: "C+",
    laws: "C+",
    english: "C",
    informationTech: "B",
    link: "/bank",
  },
  {
    id: 14,
    name: "Vidone",
    lastName: "Keophongsit",
    photo: "https://i.postimg.cc/NF5BHfSb/vidone.jpg",
    generalComputing: "A",
    mathematics: "B",
    computerRepair: "B+",
    laws: "A",
    english: "B",
    informationTech: "B",
    link: "/vidone",
  },
  {
    id: 15,
    name: "Khumphou",
    lastName: "Koumphonphukdy",
    photo: "https://i.postimg.cc/kXR7MGxg/jua.jpg",
    generalComputing: "A",
    mathematics: "C+",
    computerRepair: "B",
    laws: "A",
    english: "C+",
    informationTech: "B+",
    link: "/jua",
  },
];
